[package]
name = "fert-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
dialoguer = "0.10"
crossterm = "0.23"
accurate = { version = "0.3.1", features = [] }