# Macro elements
[N]
molar_mass = 14.007
aliases =  ["NO3", "NH4"]
priority = 100

[P]
molar_mass = 30.974
aliases = ["PO4", "P2O5"]
priority = 90

[K]
molar_mass = 39.0983
aliases = ["K2O"]
priority = 80

[S]
molar_mass = 32.065
aliases = ["SO4"]

[Ca]
molar_mass = 40.078
aliases = ["CaO"]

[Mg]
molar_mass = 24.305
aliases = ["MgO"]
priority = 40

# Micro elements
[Fe]
molar_mass = 55.845
priority = 30
[Mn]
molar_mass = 54.938
priority = 29
[Zn]
molar_mass = 65.380
priority = 28
[B]
molar_mass = 10.811
priority = 27
[Cu]
molar_mass = 63.546
[Mo]
molar_mass = 95.95
[Ni]
molar_mass = 58.693

# Insignificant elements
[H]
molar_mass = 1.0078
insignificant = true

[O]
molar_mass = 15.999
insignificant = true

[C]
molar_mass = 12.011
insignificant = true

# Ballast elements
[Cl]
molar_mass = 35.453

[Na]
molar_mass = 22.99
